# Bun configuration file
[install]
# Optimize for faster installs
cache = true
# Use exact versions from lockfile  
exact = true
# Auto-install peer dependencies
auto = true
# Prefer local registry when available
registry = "https://registry.npmjs.org"

[install.scopes]
# Configure scoped package registries if needed

[run]
# Enable shell completion for bun run
shell = "bun"

[dev]
# Hot reload configuration
hot = true